# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reddit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creddit.proto\x12\x0breddit.user\"\x13\n\x04User\x12\x0b\n\x03UID\x18\x01 \x01(\t\"\xae\x01\n\x04Post\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x05\x12*\n\x05state\x18\x04 \x01(\x0e\x32\x1b.reddit.user.Post.PostState\x12\x11\n\tpublished\x18\x05 \x01(\t\x12\n\n\x02ID\x18\x06 \x01(\t\"/\n\tPostState\x12\n\n\x06NORMAL\x10\x00\x12\n\n\x06LOCKED\x10\x01\x12\n\n\x06HIDDEN\x10\x02\"\xa8\x01\n\x07\x43omment\x12!\n\x06\x61uthor\x18\x01 \x01(\x0b\x32\x11.reddit.user.User\x12\r\n\x05score\x18\x02 \x01(\t\x12\x30\n\x05state\x18\x03 \x01(\x0e\x32!.reddit.user.Comment.CommentState\x12\x11\n\tpublished\x18\x04 \x01(\t\"&\n\x0c\x43ommentState\x12\n\n\x06NORMAL\x10\x00\x12\n\n\x06HIDDEN\x10\x01\"<\n\x0eNewPostRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t2M\n\x0bPostService\x12>\n\nCreatePost\x12\x1b.reddit.user.NewPostRequest\x1a\x11.reddit.user.Post\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reddit_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=29
  _globals['_USER']._serialized_end=48
  _globals['_POST']._serialized_start=51
  _globals['_POST']._serialized_end=225
  _globals['_POST_POSTSTATE']._serialized_start=178
  _globals['_POST_POSTSTATE']._serialized_end=225
  _globals['_COMMENT']._serialized_start=228
  _globals['_COMMENT']._serialized_end=396
  _globals['_COMMENT_COMMENTSTATE']._serialized_start=358
  _globals['_COMMENT_COMMENTSTATE']._serialized_end=396
  _globals['_NEWPOSTREQUEST']._serialized_start=398
  _globals['_NEWPOSTREQUEST']._serialized_end=458
  _globals['_POSTSERVICE']._serialized_start=460
  _globals['_POSTSERVICE']._serialized_end=537
# @@protoc_insertion_point(module_scope)
